### PR TITLE
Add Provider and UsernameLower

### PR DESCRIPTION
**Pull request by madsi1m**

### CODE REVIEW

**Comment by labkode** [comment]
@madsi1m maybe those tests can be done solely by using the builtin functions available in this library:

http://masterminds.github.io/sprig/

The template will support any of the functions available in that library and I'm sure the lib contains functions to split strings and also to lower case a string

**Comment by madsi1m** [comment]
Wow so much choice in sprig, love it.

I guess for `Provider` i could use `{{ (split \"@\" .Username)._1 }}` but looks like a mess and doesn't account for when a username isn't and email, so kept `Provider` I rather have our reva config files easy to read

**Comment by labkode** [comment]
@madsi1m One questions before merging: the Provider comes from the User struct in the UserId.IdP fields, which is usually the Provider (cern.ch/auth/realm) for example.

You use case is that the "username" is given like "peter@university.com" right?

**Comment by madsi1m** [comment]
@labkode in our case the idp is actually our simplesamlphp instance and our usernames are emails.
So in our case UserId.IdP is always the same for all users.

**Comment by labkode** [comment]
@madsi1m so as you deal with emails as usernames, then I propose you the following:

A mail like peter@example.org consists of:
* local-part: peter
* domain: example.org

Can you add a new Email field to the struct:

```
type UserData struct {
	*userpb.User
	Email EmailData 
}

type EmailData struct {
  Local string 
  Domain string
}
```

**Comment by madsi1m** [comment]
@labkode good idea, committed

**Pull request merged**
